"""Compatibility re-export layer for legacy imports.

The implementation now lives in smaller modules:
- utils.data_pipeline
- utils.modeling
"""

from utils.data_pipeline import (
    create_identifier,
    create_identifier_column_dynamic,
    create_synthetic_data_splits,
    export_gma_results,
    get_cache_path,
    get_not_reidentified_df,
    greedy_reconstruction,
    load_dataframe,
    load_experiment_datasets,
    load_not_reidentified_data,
    read_header,
    read_tsv,
    reidentification_analysis,
    resolve_encoded_dataset_path,
    run_reidentification_greedy,
    save_tsv,
)
from utils.modeling import (
    KEYS_TO_REMOVE,
    calculate_performance_metrics,
    clean_result_dict,
    decode_labels_to_bi_grams,
    dice_coefficient,
    filter_high_scoring_bi_grams,
    get_hashes,
    jaccard_similarity,
    log_epoch_metrics,
    map_probabilities_to_bi_grams,
    metrics_per_entry,
    plot_loss_curves,
    plot_metric_distributions,
    precision_recall_f1,
    print_and_save_result,
    resolve_config,
    run_epoch,
    save_nepal_runtime_log,
    to_minutes,
)

__all__ = [
    "KEYS_TO_REMOVE",
    "calculate_performance_metrics",
    "clean_result_dict",
    "create_identifier",
    "create_identifier_column_dynamic",
    "create_synthetic_data_splits",
    "decode_labels_to_bi_grams",
    "dice_coefficient",
    "export_gma_results",
    "filter_high_scoring_bi_grams",
    "get_cache_path",
    "get_hashes",
    "get_not_reidentified_df",
    "greedy_reconstruction",
    "jaccard_similarity",
    "load_dataframe",
    "load_experiment_datasets",
    "load_not_reidentified_data",
    "log_epoch_metrics",
    "map_probabilities_to_bi_grams",
    "metrics_per_entry",
    "plot_loss_curves",
    "plot_metric_distributions",
    "precision_recall_f1",
    "print_and_save_result",
    "read_header",
    "read_tsv",
    "reidentification_analysis",
    "resolve_config",
    "resolve_encoded_dataset_path",
    "run_epoch",
    "run_reidentification_greedy",
    "save_nepal_runtime_log",
    "save_tsv",
    "to_minutes",
]
